services:
  tarantool:
    container_name: tarantool_001
    image: tarantool/tarantool:3.4
    ports:
      - "3301:3301"
    environment:
      TARANTOOL_USER_NAME: probeuser
      TARANTOOL_USER_PASSWORD: 1234qwerASDF
    volumes:
      - tarantool_data:/var/lib/tarantool
      - ./tarantool:/opt/tarantool
    restart: unless-stopped
    command: ["tarantool", "/opt/tarantool/init.lua"]
    healthcheck:
      test:
        [
          "CMD",
          "tarantool",
          "-e",
          "require('console').connect('probeuser:1234qwerASDF@localhost:3301')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kv-network

  kv-service:
    container_name: kv_service_001
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - KV_CONFIG_PATH=../configs/docker.yml
    volumes:
      - ../configs/docker.yml:/configs/docker.yml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/server", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - kv-network

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.25.2
    ports:
      - "8016:8080"
    environment:
      SWAGGER_JSON: /oas/openapi.yml
    volumes:
      - ../api:/oas

volumes:
  tarantool_data:
    driver: local

networks:
  kv-network:
    driver: bridge
