env: prod
tarantool:
  host: tarantool
  port: 3301
  user: "probeuser"
  password: "1234qwerASDF"
  timeout: 5s
  kv_space: "kv"
  kv_index: "primary"
http:
  port: 8008
  kv_base_path: "/api/v1/kv"
  timeout: 5s
